import type { Metadata } from "next";
import { Archivo, Inter } from "next/font/google";
import "./globals.css";
import Navbars from "./Components/Navbar";

const inter = Inter({ subsets: ["latin"] });
const archivo = Archivo({subsets: ["latin"]})

export const metadata: Metadata = {
  title: "Mythic-Wings",
  description: "Generated by TawabMalikx by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${archivo.className}`}>
        <Navbars/>
        {children}
        </body>
    </html>
  );
}
